id: P001687
initial_creation_type: ocr
source_metadata:
  id: bdr:W3CN4894
  title: 'བྱང་ཆུབ་སེམས་དཔའི་སྤྱོད་པ་ལ་འཇུག་པའི་རྩ་འགྲེལ།

    '
  author: ''
  volumes:
    672fb5ea5d104d5d913057096e3f6c74:
      image_group_id: I3CN4896
      title: ''
      volume_number: 1
      total_pages: 556
